backend:
  name: github
  repo: bgradin/public-docs
collections:
  - name: pages
    label: Pages
    folder: docs
    create: true
    extension: md
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
        required: false
      - label: Featured Image
        name: thumbnail
        required: false
        widget: image
      - label: Body
        name: body
        widget: markdown
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
site_url: https://elmhursthoa.com
